<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Wukong.Application\Wukong.Application.csproj" />
    <ProjectReference Include="..\..\src\Wukong.Contracts\Wukong.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Wukong.Infrastructure\Wukong.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
